repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        name: black (python)

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8 (python)
        args: [
          --toml-config=./pyproject.toml,
        ]
        additional_dependencies: [
          Flake8-pyproject==1.2.3,
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
      - id: mypy
        name: mypy (python)
        files: 'src'
        additional_dependencies: [
          pydantic==2.6.4,
          types-redis==4.6.0.11,
        ]
