version: '3.7'

services:
  uvicorn:
    build:
      context: ./tlparser
      dockerfile: ./Dockerfile
    entrypoint:
      - ./entrypoint.sh
    hostname: uvicorn
    container_name: uvicorn
    ports:
      - 8000:${WEB_UVICORN_PORT}
    env_file:
    - ./env/development/.env.dev.web
    volumes:
      - ./certs/development:/code/certs:ro/
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://localhost:${WEB_UVICORN_PORT}/api/v1/docs"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      back-dev:
        ipv4_address: 192.168.10.10
    links:
      - kafka
      - mongo
      - elastic
      - redis
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
