name: Cache

on:
  workflow_call:
  push:
    paths:
      - 'poetry.lock'

jobs:
  cache:
    name: Cache dependencies for all jobs

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
      - name: clone github repository
        uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: 'poetry'

      - name: install dependencies
        run: poetry install --no-ansi --no-interaction --no-root
