name: CI

on: [push, pull_request]


jobs:
  cache:
    runs-on: [ubuntu-latest]

    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: install poetry
        run: pip install poetry

      - name: install dependencies
        run: poetry install --no-ansi --no-interaction --no-root

      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'poetry'
          cache-dependency-path: 'poetry.lock'

  lint:
    needs: build

    runs-on: [ubuntu-latest]

    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'poetry'
          cache-dependency-path: 'poetry.lock'

      - name: run linters
        run: poetry run pre-commit run --all-files
