name: CI

on:
  push:
  pull_request:
    branches:
      - master
      - dev


jobs:
  cache:
    name: cache dependencies for all jobs

    runs-on: [ubuntu-latest]

    steps:
      - name: clone github repository
        uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'poetry'

      - name: install dependencies
        run: poetry install --no-ansi --no-interaction --no-root

  lint:
    name: run linting and formatting checks

    needs: cache

    runs-on: [ubuntu-latest]

    steps:
      - name: clone github repository
        uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - name: install python3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'poetry'

      - name: run linters
        run: poetry run pre-commit run --all-files
