name: CI

on:
  push:
  pull_request:
    branches: [master, dev]


env:
  POETRY_VERSION: 1.7.1

jobs:
  cache:
    name: cache poetry installation, poetry.lock file and dependencies for all jobs

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: cache poetry installation
        id: cached-poetry                 # need to check from another step if there is a cache hit.
        uses: actions/cache@v4
        with:
          path: ~/.local
          key:  python${{ matrix.python-version }}:poetry${{ env.POETRY_VERSION }}-key

      - name: install poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'   # install only if there is not a cache hit (possible when poetry version has changed)
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: clone github repository
        uses: actions/checkout@v4

      - name: cache poetry.lock file
        id: cached-poetry-lock
        uses: actions/cache@v4
        with:
          path: poetry.lock
          key:  python${{ matrix.python-version }}:poetry${{ env.POETRY_VERSION }}.lock-${{ hashFiles('poetry.lock') }}-key

      - name: create poetry.lock file     # poetry.lock will be created in a repository
        if: steps.cached-poetry-lock.outputs.cache-hit != 'true'
        run: poetry lock

      - name: install python and cache poetry dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: install dependencies
        run: poetry install --no-ansi --no-interaction --no-root

  lint:
    name: Run linting and formatting checks

    needs: cache

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: clone github repository
        uses: actions/checkout@v4

      - name: restore poetry from cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key:  python${{ matrix.python-version }}-poetry1.7-key

      - name: restore poetry lock
        uses: actions/cache@v4
        with:
          path: poetry.lock
          key:  poetry-lock

      - name: install python and cache poetry dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: run linters
        run: poetry run pre-commit run --all-files

  push:
    name: Push docker image to docker hub

    needs: lint

    runs-on: ubuntu-latest

    steps:
      - name: clone github repository
        uses: actions/checkout@v4

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY }}:latest'
