name: Lint

on:
  push:
  pull_request:
    branches:
      - master
      - dev

jobs:
  call-cache-workflow:
    name: Call cache workflow
    uses: ./github/workflows/cache

  lint:
    name: Run linting and formatting checks

    needs: cache

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ['${{ matrix.os }}']

    steps:
      - name: clone github repository
        uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: 'poetry'

      - name: run linters
        run: poetry run pre-commit run --all-files
