name: Publish

on:
  workflow_run:
    workflows: [Static]
    types: [completed]
    brances: [master, dev]

jobs:
  push:
    name: Push docker image to docker hub

    runs-on: ubuntu-latest

    steps:
      - name: Clone github repository
        uses: actions/checkout@v4

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY }}:latest'
